idf_component_register(
    SRCS "display.c"
         "ui_task.cpp"
         "ui_screen_logic.c"
         "screens/home_screen.cpp"
         "screens/recording_screen.cpp"
         "screens/menu.c"
         "screens/list_pagination.c"
         "screens/recordings_list.c"
         "screens/unsent_list.c"
         "screens/info_screen.c"
         "face_engine/face_registry.cpp"
         "face_engine/owl_face.cpp"
         "face_engine/minimal_face.cpp"
         "face_engine/robot_face.cpp"
         "face_engine/pixel_face.cpp"
         "face_engine/vector_face.cpp"
    INCLUDE_DIRS "include"
                 "face_engine"
                 "face_engine/include"
    REQUIRES esp_driver_spi esp_lcd board log esp_event recorder audio esp_timer storage network
)
